### ISSUE TITLE
Adjust code style

### ISSUE THREAD

**Issue by LKodex** [falcao-g/processo-mega#7]
Code style need to be adjusted with eslint

`npx eslint src/**/*.js --fix`

Also the `no-console` eslint rule can be disabled

**Comment by falcao-g** [comment]
we can setup a hook so that when we run git commit it automatically fixes all eslint errors

**Comment by LKodex** [comment]
Sounds good, can you do it?

**Comment by falcao-g** [comment]
yeah, i will add it
